import { getUser } from "@/auth";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import styles from "./layout.module.scss";
import { HeadNav } from "./HeadNav";
import BlobBackground from "@/components/backgrounds/BlobBackground";
import Circle from "@/components/shapes/Circle";
import { SideNav } from "./SideNav";
import Button from "@/components/ui/Button";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    if ((await getUser(cookies().get("currentUser")?.value ?? "")) == null)
        return redirect("/login");

    const sideNavLinks = [
        { name: <Button className={styles.navButton}>Home</Button>, href: "/dashboard" },
        { name: <Button className={styles.navButton}>Priority definer</Button>, href: "/dashboard/priority" },
        { name: <Button className={styles.navButton}>Page editor</Button>, href: "/dashboard/editor" },
        { name: <Button className={styles.navButton}>UI Test</Button>, href: "/dashboard/ui-test" },
    ];

    return (
        <>
            <div className={styles.background}>
                <BlobBackground
                    blobBackground="#000"
                    blobColor1="var(--accent)"
                    blobColor2="var(--accent-disabled)"
                    blobScale={1.5}
                    blurSize={0}
                    shape={Circle}
                />
            </div>

            <div className={styles.sideNavContainer}>
                <SideNav links={sideNavLinks} />
                <div className={styles.headNavContainer}>
                    <HeadNav />
                    <div className={styles.content}>{children}</div>
                </div>
            </div>
        </>
    );
}
